[project]
name = "autopost-agent"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "openai>=1.99.1",
    "requests>=2.32.4",
    "tweepy>=4.16.0",
]
